// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: smtp.proto

#include "smtp.pb.h"
#include "smtp.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace SMTP {
namespace Captcha {

static const char* Send_Captcha_method_names[] = {
  "/SMTP.Captcha.Send_Captcha/SendCaptcha",
};

std::unique_ptr< Send_Captcha::Stub> Send_Captcha::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Send_Captcha::Stub> stub(new Send_Captcha::Stub(channel, options));
  return stub;
}

Send_Captcha::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendCaptcha_(Send_Captcha_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Send_Captcha::Stub::SendCaptcha(::grpc::ClientContext* context, const ::SMTP::Captcha::SMTP_Captcha_Req& request, ::SMTP::Captcha::SMTP_Captcha_Rsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::SMTP::Captcha::SMTP_Captcha_Req, ::SMTP::Captcha::SMTP_Captcha_Rsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendCaptcha_, context, request, response);
}

void Send_Captcha::Stub::async::SendCaptcha(::grpc::ClientContext* context, const ::SMTP::Captcha::SMTP_Captcha_Req* request, ::SMTP::Captcha::SMTP_Captcha_Rsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::SMTP::Captcha::SMTP_Captcha_Req, ::SMTP::Captcha::SMTP_Captcha_Rsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendCaptcha_, context, request, response, std::move(f));
}

void Send_Captcha::Stub::async::SendCaptcha(::grpc::ClientContext* context, const ::SMTP::Captcha::SMTP_Captcha_Req* request, ::SMTP::Captcha::SMTP_Captcha_Rsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendCaptcha_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::SMTP::Captcha::SMTP_Captcha_Rsp>* Send_Captcha::Stub::PrepareAsyncSendCaptchaRaw(::grpc::ClientContext* context, const ::SMTP::Captcha::SMTP_Captcha_Req& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::SMTP::Captcha::SMTP_Captcha_Rsp, ::SMTP::Captcha::SMTP_Captcha_Req, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendCaptcha_, context, request);
}

::grpc::ClientAsyncResponseReader< ::SMTP::Captcha::SMTP_Captcha_Rsp>* Send_Captcha::Stub::AsyncSendCaptchaRaw(::grpc::ClientContext* context, const ::SMTP::Captcha::SMTP_Captcha_Req& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendCaptchaRaw(context, request, cq);
  result->StartCall();
  return result;
}

Send_Captcha::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Send_Captcha_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Send_Captcha::Service, ::SMTP::Captcha::SMTP_Captcha_Req, ::SMTP::Captcha::SMTP_Captcha_Rsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Send_Captcha::Service* service,
             ::grpc::ServerContext* ctx,
             const ::SMTP::Captcha::SMTP_Captcha_Req* req,
             ::SMTP::Captcha::SMTP_Captcha_Rsp* resp) {
               return service->SendCaptcha(ctx, req, resp);
             }, this)));
}

Send_Captcha::Service::~Service() {
}

::grpc::Status Send_Captcha::Service::SendCaptcha(::grpc::ServerContext* context, const ::SMTP::Captcha::SMTP_Captcha_Req* request, ::SMTP::Captcha::SMTP_Captcha_Rsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace SMTP
}  // namespace Captcha

