// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smtp.proto

#include "smtp.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace SMTP {
namespace Captcha {
constexpr SMTP_Captcha_Req::SMTP_Captcha_Req(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : emails_()
  , captcha_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct SMTP_Captcha_ReqDefaultTypeInternal {
  constexpr SMTP_Captcha_ReqDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SMTP_Captcha_ReqDefaultTypeInternal() {}
  union {
    SMTP_Captcha_Req _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SMTP_Captcha_ReqDefaultTypeInternal _SMTP_Captcha_Req_default_instance_;
constexpr SMTP_Captcha_Rsp::SMTP_Captcha_Rsp(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : code_(0u){}
struct SMTP_Captcha_RspDefaultTypeInternal {
  constexpr SMTP_Captcha_RspDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SMTP_Captcha_RspDefaultTypeInternal() {}
  union {
    SMTP_Captcha_Rsp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SMTP_Captcha_RspDefaultTypeInternal _SMTP_Captcha_Rsp_default_instance_;
}  // namespace Captcha
}  // namespace SMTP
namespace SMTP {
namespace Captcha {

// ===================================================================

class SMTP_Captcha_Req::_Internal {
 public:
};

SMTP_Captcha_Req::SMTP_Captcha_Req(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned),
  emails_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:SMTP.Captcha.SMTP_Captcha_Req)
}
SMTP_Captcha_Req::SMTP_Captcha_Req(const SMTP_Captcha_Req& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      emails_(from.emails_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  captcha_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    captcha_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_captcha().empty()) {
    captcha_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_captcha(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:SMTP.Captcha.SMTP_Captcha_Req)
}

inline void SMTP_Captcha_Req::SharedCtor() {
captcha_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  captcha_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SMTP_Captcha_Req::~SMTP_Captcha_Req() {
  // @@protoc_insertion_point(destructor:SMTP.Captcha.SMTP_Captcha_Req)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<std::string>();
}

inline void SMTP_Captcha_Req::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  captcha_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void SMTP_Captcha_Req::ArenaDtor(void* object) {
  SMTP_Captcha_Req* _this = reinterpret_cast< SMTP_Captcha_Req* >(object);
  (void)_this;
}
void SMTP_Captcha_Req::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SMTP_Captcha_Req::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SMTP_Captcha_Req::Clear() {
// @@protoc_insertion_point(message_clear_start:SMTP.Captcha.SMTP_Captcha_Req)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  emails_.Clear();
  captcha_.ClearToEmpty();
  _internal_metadata_.Clear<std::string>();
}

const char* SMTP_Captcha_Req::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated string emails = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_emails();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, nullptr));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // string captcha = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_captcha();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, nullptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SMTP_Captcha_Req::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SMTP.Captcha.SMTP_Captcha_Req)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string emails = 1;
  for (int i = 0, n = this->_internal_emails_size(); i < n; i++) {
    const auto& s = this->_internal_emails(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "SMTP.Captcha.SMTP_Captcha_Req.emails");
    target = stream->WriteString(1, s, target);
  }

  // string captcha = 2;
  if (!this->_internal_captcha().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_captcha().data(), static_cast<int>(this->_internal_captcha().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "SMTP.Captcha.SMTP_Captcha_Req.captcha");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_captcha(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SMTP.Captcha.SMTP_Captcha_Req)
  return target;
}

size_t SMTP_Captcha_Req::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SMTP.Captcha.SMTP_Captcha_Req)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string emails = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(emails_.size());
  for (int i = 0, n = emails_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      emails_.Get(i));
  }

  // string captcha = 2;
  if (!this->_internal_captcha().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_captcha());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SMTP_Captcha_Req::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::PROTOBUF_NAMESPACE_ID::internal::DownCast<const SMTP_Captcha_Req*>(
      &from));
}

void SMTP_Captcha_Req::MergeFrom(const SMTP_Captcha_Req& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:SMTP.Captcha.SMTP_Captcha_Req)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  emails_.MergeFrom(from.emails_);
  if (!from._internal_captcha().empty()) {
    _internal_set_captcha(from._internal_captcha());
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void SMTP_Captcha_Req::CopyFrom(const SMTP_Captcha_Req& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SMTP.Captcha.SMTP_Captcha_Req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SMTP_Captcha_Req::IsInitialized() const {
  return true;
}

void SMTP_Captcha_Req::InternalSwap(SMTP_Captcha_Req* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  emails_.InternalSwap(&other->emails_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &captcha_, lhs_arena,
      &other->captcha_, rhs_arena
  );
}

std::string SMTP_Captcha_Req::GetTypeName() const {
  return "SMTP.Captcha.SMTP_Captcha_Req";
}


// ===================================================================

class SMTP_Captcha_Rsp::_Internal {
 public:
};

SMTP_Captcha_Rsp::SMTP_Captcha_Rsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:SMTP.Captcha.SMTP_Captcha_Rsp)
}
SMTP_Captcha_Rsp::SMTP_Captcha_Rsp(const SMTP_Captcha_Rsp& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  code_ = from.code_;
  // @@protoc_insertion_point(copy_constructor:SMTP.Captcha.SMTP_Captcha_Rsp)
}

inline void SMTP_Captcha_Rsp::SharedCtor() {
code_ = 0u;
}

SMTP_Captcha_Rsp::~SMTP_Captcha_Rsp() {
  // @@protoc_insertion_point(destructor:SMTP.Captcha.SMTP_Captcha_Rsp)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<std::string>();
}

inline void SMTP_Captcha_Rsp::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SMTP_Captcha_Rsp::ArenaDtor(void* object) {
  SMTP_Captcha_Rsp* _this = reinterpret_cast< SMTP_Captcha_Rsp* >(object);
  (void)_this;
}
void SMTP_Captcha_Rsp::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SMTP_Captcha_Rsp::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SMTP_Captcha_Rsp::Clear() {
// @@protoc_insertion_point(message_clear_start:SMTP.Captcha.SMTP_Captcha_Rsp)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  code_ = 0u;
  _internal_metadata_.Clear<std::string>();
}

const char* SMTP_Captcha_Rsp::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SMTP_Captcha_Rsp::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SMTP.Captcha.SMTP_Captcha_Rsp)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 code = 1;
  if (this->_internal_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_code(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SMTP.Captcha.SMTP_Captcha_Rsp)
  return target;
}

size_t SMTP_Captcha_Rsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SMTP.Captcha.SMTP_Captcha_Rsp)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 code = 1;
  if (this->_internal_code() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_code());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SMTP_Captcha_Rsp::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::PROTOBUF_NAMESPACE_ID::internal::DownCast<const SMTP_Captcha_Rsp*>(
      &from));
}

void SMTP_Captcha_Rsp::MergeFrom(const SMTP_Captcha_Rsp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:SMTP.Captcha.SMTP_Captcha_Rsp)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_code() != 0) {
    _internal_set_code(from._internal_code());
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void SMTP_Captcha_Rsp::CopyFrom(const SMTP_Captcha_Rsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SMTP.Captcha.SMTP_Captcha_Rsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SMTP_Captcha_Rsp::IsInitialized() const {
  return true;
}

void SMTP_Captcha_Rsp::InternalSwap(SMTP_Captcha_Rsp* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(code_, other->code_);
}

std::string SMTP_Captcha_Rsp::GetTypeName() const {
  return "SMTP.Captcha.SMTP_Captcha_Rsp";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Captcha
}  // namespace SMTP
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::SMTP::Captcha::SMTP_Captcha_Req* Arena::CreateMaybeMessage< ::SMTP::Captcha::SMTP_Captcha_Req >(Arena* arena) {
  return Arena::CreateMessageInternal< ::SMTP::Captcha::SMTP_Captcha_Req >(arena);
}
template<> PROTOBUF_NOINLINE ::SMTP::Captcha::SMTP_Captcha_Rsp* Arena::CreateMaybeMessage< ::SMTP::Captcha::SMTP_Captcha_Rsp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::SMTP::Captcha::SMTP_Captcha_Rsp >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
