// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smtp.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_smtp_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_smtp_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_smtp_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_smtp_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
namespace SMTP {
namespace Captcha {
class SMTP_Captcha_Req;
struct SMTP_Captcha_ReqDefaultTypeInternal;
extern SMTP_Captcha_ReqDefaultTypeInternal _SMTP_Captcha_Req_default_instance_;
class SMTP_Captcha_Rsp;
struct SMTP_Captcha_RspDefaultTypeInternal;
extern SMTP_Captcha_RspDefaultTypeInternal _SMTP_Captcha_Rsp_default_instance_;
}  // namespace Captcha
}  // namespace SMTP
PROTOBUF_NAMESPACE_OPEN
template<> ::SMTP::Captcha::SMTP_Captcha_Req* Arena::CreateMaybeMessage<::SMTP::Captcha::SMTP_Captcha_Req>(Arena*);
template<> ::SMTP::Captcha::SMTP_Captcha_Rsp* Arena::CreateMaybeMessage<::SMTP::Captcha::SMTP_Captcha_Rsp>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace SMTP {
namespace Captcha {

// ===================================================================

class SMTP_Captcha_Req final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:SMTP.Captcha.SMTP_Captcha_Req) */ {
 public:
  inline SMTP_Captcha_Req() : SMTP_Captcha_Req(nullptr) {}
  ~SMTP_Captcha_Req() override;
  explicit constexpr SMTP_Captcha_Req(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SMTP_Captcha_Req(const SMTP_Captcha_Req& from);
  SMTP_Captcha_Req(SMTP_Captcha_Req&& from) noexcept
    : SMTP_Captcha_Req() {
    *this = ::std::move(from);
  }

  inline SMTP_Captcha_Req& operator=(const SMTP_Captcha_Req& from) {
    CopyFrom(from);
    return *this;
  }
  inline SMTP_Captcha_Req& operator=(SMTP_Captcha_Req&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const SMTP_Captcha_Req& default_instance() {
    return *internal_default_instance();
  }
  static inline const SMTP_Captcha_Req* internal_default_instance() {
    return reinterpret_cast<const SMTP_Captcha_Req*>(
               &_SMTP_Captcha_Req_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SMTP_Captcha_Req& a, SMTP_Captcha_Req& b) {
    a.Swap(&b);
  }
  inline void Swap(SMTP_Captcha_Req* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SMTP_Captcha_Req* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SMTP_Captcha_Req* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SMTP_Captcha_Req>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const SMTP_Captcha_Req& from);
  void MergeFrom(const SMTP_Captcha_Req& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SMTP_Captcha_Req* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SMTP.Captcha.SMTP_Captcha_Req";
  }
  protected:
  explicit SMTP_Captcha_Req(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEmailsFieldNumber = 1,
    kCaptchaFieldNumber = 2,
  };
  // repeated string emails = 1;
  int emails_size() const;
  private:
  int _internal_emails_size() const;
  public:
  void clear_emails();
  const std::string& emails(int index) const;
  std::string* mutable_emails(int index);
  void set_emails(int index, const std::string& value);
  void set_emails(int index, std::string&& value);
  void set_emails(int index, const char* value);
  void set_emails(int index, const char* value, size_t size);
  std::string* add_emails();
  void add_emails(const std::string& value);
  void add_emails(std::string&& value);
  void add_emails(const char* value);
  void add_emails(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& emails() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_emails();
  private:
  const std::string& _internal_emails(int index) const;
  std::string* _internal_add_emails();
  public:

  // string captcha = 2;
  void clear_captcha();
  const std::string& captcha() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_captcha(ArgT0&& arg0, ArgT... args);
  std::string* mutable_captcha();
  PROTOBUF_NODISCARD std::string* release_captcha();
  void set_allocated_captcha(std::string* captcha);
  private:
  const std::string& _internal_captcha() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_captcha(const std::string& value);
  std::string* _internal_mutable_captcha();
  public:

  // @@protoc_insertion_point(class_scope:SMTP.Captcha.SMTP_Captcha_Req)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> emails_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr captcha_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_smtp_2eproto;
};
// -------------------------------------------------------------------

class SMTP_Captcha_Rsp final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:SMTP.Captcha.SMTP_Captcha_Rsp) */ {
 public:
  inline SMTP_Captcha_Rsp() : SMTP_Captcha_Rsp(nullptr) {}
  ~SMTP_Captcha_Rsp() override;
  explicit constexpr SMTP_Captcha_Rsp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SMTP_Captcha_Rsp(const SMTP_Captcha_Rsp& from);
  SMTP_Captcha_Rsp(SMTP_Captcha_Rsp&& from) noexcept
    : SMTP_Captcha_Rsp() {
    *this = ::std::move(from);
  }

  inline SMTP_Captcha_Rsp& operator=(const SMTP_Captcha_Rsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline SMTP_Captcha_Rsp& operator=(SMTP_Captcha_Rsp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const SMTP_Captcha_Rsp& default_instance() {
    return *internal_default_instance();
  }
  static inline const SMTP_Captcha_Rsp* internal_default_instance() {
    return reinterpret_cast<const SMTP_Captcha_Rsp*>(
               &_SMTP_Captcha_Rsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SMTP_Captcha_Rsp& a, SMTP_Captcha_Rsp& b) {
    a.Swap(&b);
  }
  inline void Swap(SMTP_Captcha_Rsp* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SMTP_Captcha_Rsp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SMTP_Captcha_Rsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SMTP_Captcha_Rsp>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const SMTP_Captcha_Rsp& from);
  void MergeFrom(const SMTP_Captcha_Rsp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SMTP_Captcha_Rsp* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SMTP.Captcha.SMTP_Captcha_Rsp";
  }
  protected:
  explicit SMTP_Captcha_Rsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCodeFieldNumber = 1,
  };
  // uint32 code = 1;
  void clear_code();
  uint32_t code() const;
  void set_code(uint32_t value);
  private:
  uint32_t _internal_code() const;
  void _internal_set_code(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:SMTP.Captcha.SMTP_Captcha_Rsp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  uint32_t code_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_smtp_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SMTP_Captcha_Req

// repeated string emails = 1;
inline int SMTP_Captcha_Req::_internal_emails_size() const {
  return emails_.size();
}
inline int SMTP_Captcha_Req::emails_size() const {
  return _internal_emails_size();
}
inline void SMTP_Captcha_Req::clear_emails() {
  emails_.Clear();
}
inline std::string* SMTP_Captcha_Req::add_emails() {
  std::string* _s = _internal_add_emails();
  // @@protoc_insertion_point(field_add_mutable:SMTP.Captcha.SMTP_Captcha_Req.emails)
  return _s;
}
inline const std::string& SMTP_Captcha_Req::_internal_emails(int index) const {
  return emails_.Get(index);
}
inline const std::string& SMTP_Captcha_Req::emails(int index) const {
  // @@protoc_insertion_point(field_get:SMTP.Captcha.SMTP_Captcha_Req.emails)
  return _internal_emails(index);
}
inline std::string* SMTP_Captcha_Req::mutable_emails(int index) {
  // @@protoc_insertion_point(field_mutable:SMTP.Captcha.SMTP_Captcha_Req.emails)
  return emails_.Mutable(index);
}
inline void SMTP_Captcha_Req::set_emails(int index, const std::string& value) {
  emails_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:SMTP.Captcha.SMTP_Captcha_Req.emails)
}
inline void SMTP_Captcha_Req::set_emails(int index, std::string&& value) {
  emails_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:SMTP.Captcha.SMTP_Captcha_Req.emails)
}
inline void SMTP_Captcha_Req::set_emails(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  emails_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:SMTP.Captcha.SMTP_Captcha_Req.emails)
}
inline void SMTP_Captcha_Req::set_emails(int index, const char* value, size_t size) {
  emails_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:SMTP.Captcha.SMTP_Captcha_Req.emails)
}
inline std::string* SMTP_Captcha_Req::_internal_add_emails() {
  return emails_.Add();
}
inline void SMTP_Captcha_Req::add_emails(const std::string& value) {
  emails_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:SMTP.Captcha.SMTP_Captcha_Req.emails)
}
inline void SMTP_Captcha_Req::add_emails(std::string&& value) {
  emails_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:SMTP.Captcha.SMTP_Captcha_Req.emails)
}
inline void SMTP_Captcha_Req::add_emails(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  emails_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:SMTP.Captcha.SMTP_Captcha_Req.emails)
}
inline void SMTP_Captcha_Req::add_emails(const char* value, size_t size) {
  emails_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:SMTP.Captcha.SMTP_Captcha_Req.emails)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
SMTP_Captcha_Req::emails() const {
  // @@protoc_insertion_point(field_list:SMTP.Captcha.SMTP_Captcha_Req.emails)
  return emails_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
SMTP_Captcha_Req::mutable_emails() {
  // @@protoc_insertion_point(field_mutable_list:SMTP.Captcha.SMTP_Captcha_Req.emails)
  return &emails_;
}

// string captcha = 2;
inline void SMTP_Captcha_Req::clear_captcha() {
  captcha_.ClearToEmpty();
}
inline const std::string& SMTP_Captcha_Req::captcha() const {
  // @@protoc_insertion_point(field_get:SMTP.Captcha.SMTP_Captcha_Req.captcha)
  return _internal_captcha();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SMTP_Captcha_Req::set_captcha(ArgT0&& arg0, ArgT... args) {
 
 captcha_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SMTP.Captcha.SMTP_Captcha_Req.captcha)
}
inline std::string* SMTP_Captcha_Req::mutable_captcha() {
  std::string* _s = _internal_mutable_captcha();
  // @@protoc_insertion_point(field_mutable:SMTP.Captcha.SMTP_Captcha_Req.captcha)
  return _s;
}
inline const std::string& SMTP_Captcha_Req::_internal_captcha() const {
  return captcha_.Get();
}
inline void SMTP_Captcha_Req::_internal_set_captcha(const std::string& value) {
  
  captcha_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* SMTP_Captcha_Req::_internal_mutable_captcha() {
  
  return captcha_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* SMTP_Captcha_Req::release_captcha() {
  // @@protoc_insertion_point(field_release:SMTP.Captcha.SMTP_Captcha_Req.captcha)
  return captcha_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void SMTP_Captcha_Req::set_allocated_captcha(std::string* captcha) {
  if (captcha != nullptr) {
    
  } else {
    
  }
  captcha_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), captcha,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (captcha_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    captcha_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SMTP.Captcha.SMTP_Captcha_Req.captcha)
}

// -------------------------------------------------------------------

// SMTP_Captcha_Rsp

// uint32 code = 1;
inline void SMTP_Captcha_Rsp::clear_code() {
  code_ = 0u;
}
inline uint32_t SMTP_Captcha_Rsp::_internal_code() const {
  return code_;
}
inline uint32_t SMTP_Captcha_Rsp::code() const {
  // @@protoc_insertion_point(field_get:SMTP.Captcha.SMTP_Captcha_Rsp.code)
  return _internal_code();
}
inline void SMTP_Captcha_Rsp::_internal_set_code(uint32_t value) {
  
  code_ = value;
}
inline void SMTP_Captcha_Rsp::set_code(uint32_t value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:SMTP.Captcha.SMTP_Captcha_Rsp.code)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Captcha
}  // namespace SMTP

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_smtp_2eproto
