// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: smtp.proto
#ifndef GRPC_smtp_2eproto__INCLUDED
#define GRPC_smtp_2eproto__INCLUDED

#include "smtp.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace SMTP {
namespace Captcha {

class Send_Captcha final {
 public:
  static constexpr char const* service_full_name() {
    return "SMTP.Captcha.Send_Captcha";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SendCaptcha(::grpc::ClientContext* context, const ::SMTP::Captcha::SMTP_Captcha_Req& request, ::SMTP::Captcha::SMTP_Captcha_Rsp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMTP::Captcha::SMTP_Captcha_Rsp>> AsyncSendCaptcha(::grpc::ClientContext* context, const ::SMTP::Captcha::SMTP_Captcha_Req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMTP::Captcha::SMTP_Captcha_Rsp>>(AsyncSendCaptchaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMTP::Captcha::SMTP_Captcha_Rsp>> PrepareAsyncSendCaptcha(::grpc::ClientContext* context, const ::SMTP::Captcha::SMTP_Captcha_Req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMTP::Captcha::SMTP_Captcha_Rsp>>(PrepareAsyncSendCaptchaRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SendCaptcha(::grpc::ClientContext* context, const ::SMTP::Captcha::SMTP_Captcha_Req* request, ::SMTP::Captcha::SMTP_Captcha_Rsp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendCaptcha(::grpc::ClientContext* context, const ::SMTP::Captcha::SMTP_Captcha_Req* request, ::SMTP::Captcha::SMTP_Captcha_Rsp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SMTP::Captcha::SMTP_Captcha_Rsp>* AsyncSendCaptchaRaw(::grpc::ClientContext* context, const ::SMTP::Captcha::SMTP_Captcha_Req& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SMTP::Captcha::SMTP_Captcha_Rsp>* PrepareAsyncSendCaptchaRaw(::grpc::ClientContext* context, const ::SMTP::Captcha::SMTP_Captcha_Req& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SendCaptcha(::grpc::ClientContext* context, const ::SMTP::Captcha::SMTP_Captcha_Req& request, ::SMTP::Captcha::SMTP_Captcha_Rsp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMTP::Captcha::SMTP_Captcha_Rsp>> AsyncSendCaptcha(::grpc::ClientContext* context, const ::SMTP::Captcha::SMTP_Captcha_Req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMTP::Captcha::SMTP_Captcha_Rsp>>(AsyncSendCaptchaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMTP::Captcha::SMTP_Captcha_Rsp>> PrepareAsyncSendCaptcha(::grpc::ClientContext* context, const ::SMTP::Captcha::SMTP_Captcha_Req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMTP::Captcha::SMTP_Captcha_Rsp>>(PrepareAsyncSendCaptchaRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendCaptcha(::grpc::ClientContext* context, const ::SMTP::Captcha::SMTP_Captcha_Req* request, ::SMTP::Captcha::SMTP_Captcha_Rsp* response, std::function<void(::grpc::Status)>) override;
      void SendCaptcha(::grpc::ClientContext* context, const ::SMTP::Captcha::SMTP_Captcha_Req* request, ::SMTP::Captcha::SMTP_Captcha_Rsp* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::SMTP::Captcha::SMTP_Captcha_Rsp>* AsyncSendCaptchaRaw(::grpc::ClientContext* context, const ::SMTP::Captcha::SMTP_Captcha_Req& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::SMTP::Captcha::SMTP_Captcha_Rsp>* PrepareAsyncSendCaptchaRaw(::grpc::ClientContext* context, const ::SMTP::Captcha::SMTP_Captcha_Req& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendCaptcha_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendCaptcha(::grpc::ServerContext* context, const ::SMTP::Captcha::SMTP_Captcha_Req* request, ::SMTP::Captcha::SMTP_Captcha_Rsp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendCaptcha : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendCaptcha() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendCaptcha() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendCaptcha(::grpc::ServerContext* /*context*/, const ::SMTP::Captcha::SMTP_Captcha_Req* /*request*/, ::SMTP::Captcha::SMTP_Captcha_Rsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendCaptcha(::grpc::ServerContext* context, ::SMTP::Captcha::SMTP_Captcha_Req* request, ::grpc::ServerAsyncResponseWriter< ::SMTP::Captcha::SMTP_Captcha_Rsp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendCaptcha<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendCaptcha : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendCaptcha() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::SMTP::Captcha::SMTP_Captcha_Req, ::SMTP::Captcha::SMTP_Captcha_Rsp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::SMTP::Captcha::SMTP_Captcha_Req* request, ::SMTP::Captcha::SMTP_Captcha_Rsp* response) { return this->SendCaptcha(context, request, response); }));}
    void SetMessageAllocatorFor_SendCaptcha(
        ::grpc::MessageAllocator< ::SMTP::Captcha::SMTP_Captcha_Req, ::SMTP::Captcha::SMTP_Captcha_Rsp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::SMTP::Captcha::SMTP_Captcha_Req, ::SMTP::Captcha::SMTP_Captcha_Rsp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendCaptcha() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendCaptcha(::grpc::ServerContext* /*context*/, const ::SMTP::Captcha::SMTP_Captcha_Req* /*request*/, ::SMTP::Captcha::SMTP_Captcha_Rsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendCaptcha(
      ::grpc::CallbackServerContext* /*context*/, const ::SMTP::Captcha::SMTP_Captcha_Req* /*request*/, ::SMTP::Captcha::SMTP_Captcha_Rsp* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SendCaptcha<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendCaptcha : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendCaptcha() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendCaptcha() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendCaptcha(::grpc::ServerContext* /*context*/, const ::SMTP::Captcha::SMTP_Captcha_Req* /*request*/, ::SMTP::Captcha::SMTP_Captcha_Rsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendCaptcha : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendCaptcha() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendCaptcha() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendCaptcha(::grpc::ServerContext* /*context*/, const ::SMTP::Captcha::SMTP_Captcha_Req* /*request*/, ::SMTP::Captcha::SMTP_Captcha_Rsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendCaptcha(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendCaptcha : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendCaptcha() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendCaptcha(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendCaptcha() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendCaptcha(::grpc::ServerContext* /*context*/, const ::SMTP::Captcha::SMTP_Captcha_Req* /*request*/, ::SMTP::Captcha::SMTP_Captcha_Rsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendCaptcha(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendCaptcha : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendCaptcha() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::SMTP::Captcha::SMTP_Captcha_Req, ::SMTP::Captcha::SMTP_Captcha_Rsp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::SMTP::Captcha::SMTP_Captcha_Req, ::SMTP::Captcha::SMTP_Captcha_Rsp>* streamer) {
                       return this->StreamedSendCaptcha(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendCaptcha() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendCaptcha(::grpc::ServerContext* /*context*/, const ::SMTP::Captcha::SMTP_Captcha_Req* /*request*/, ::SMTP::Captcha::SMTP_Captcha_Rsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendCaptcha(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::SMTP::Captcha::SMTP_Captcha_Req,::SMTP::Captcha::SMTP_Captcha_Rsp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendCaptcha<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendCaptcha<Service > StreamedService;
};

}  // namespace Captcha
}  // namespace SMTP


#endif  // GRPC_smtp_2eproto__INCLUDED
