// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: smtp.proto

#include "smtp.pb.h"
#include "smtp.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace SMTP {
namespace Email_Msg {

static const char* Send_Email_Msg_method_names[] = {
  "/SMTP.Email_Msg.Send_Email_Msg/Send_Msg",
};

std::unique_ptr< Send_Email_Msg::Stub> Send_Email_Msg::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Send_Email_Msg::Stub> stub(new Send_Email_Msg::Stub(channel, options));
  return stub;
}

Send_Email_Msg::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Send_Msg_(Send_Email_Msg_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Send_Email_Msg::Stub::Send_Msg(::grpc::ClientContext* context, const ::SMTP::Email_Msg::SMTP_Req& request, ::SMTP::Email_Msg::SMTP_Rsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::SMTP::Email_Msg::SMTP_Req, ::SMTP::Email_Msg::SMTP_Rsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Send_Msg_, context, request, response);
}

void Send_Email_Msg::Stub::async::Send_Msg(::grpc::ClientContext* context, const ::SMTP::Email_Msg::SMTP_Req* request, ::SMTP::Email_Msg::SMTP_Rsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::SMTP::Email_Msg::SMTP_Req, ::SMTP::Email_Msg::SMTP_Rsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Send_Msg_, context, request, response, std::move(f));
}

void Send_Email_Msg::Stub::async::Send_Msg(::grpc::ClientContext* context, const ::SMTP::Email_Msg::SMTP_Req* request, ::SMTP::Email_Msg::SMTP_Rsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Send_Msg_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::SMTP::Email_Msg::SMTP_Rsp>* Send_Email_Msg::Stub::PrepareAsyncSend_MsgRaw(::grpc::ClientContext* context, const ::SMTP::Email_Msg::SMTP_Req& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::SMTP::Email_Msg::SMTP_Rsp, ::SMTP::Email_Msg::SMTP_Req, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Send_Msg_, context, request);
}

::grpc::ClientAsyncResponseReader< ::SMTP::Email_Msg::SMTP_Rsp>* Send_Email_Msg::Stub::AsyncSend_MsgRaw(::grpc::ClientContext* context, const ::SMTP::Email_Msg::SMTP_Req& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSend_MsgRaw(context, request, cq);
  result->StartCall();
  return result;
}

Send_Email_Msg::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Send_Email_Msg_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Send_Email_Msg::Service, ::SMTP::Email_Msg::SMTP_Req, ::SMTP::Email_Msg::SMTP_Rsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Send_Email_Msg::Service* service,
             ::grpc::ServerContext* ctx,
             const ::SMTP::Email_Msg::SMTP_Req* req,
             ::SMTP::Email_Msg::SMTP_Rsp* resp) {
               return service->Send_Msg(ctx, req, resp);
             }, this)));
}

Send_Email_Msg::Service::~Service() {
}

::grpc::Status Send_Email_Msg::Service::Send_Msg(::grpc::ServerContext* context, const ::SMTP::Email_Msg::SMTP_Req* request, ::SMTP::Email_Msg::SMTP_Rsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace SMTP
}  // namespace Email_Msg

